definitions:
  services.Assessment:
    properties:
      compatibilityPoint:
        $ref: '#/definitions/services.point'
      createdAt:
        type: string
      elasticId:
        type: string
      experiencePoint:
        type: boolean
      id:
        type: string
      jobId:
        type: string
      locationMatch:
        $ref: '#/definitions/services.match'
      requirementPoint:
        $ref: '#/definitions/services.point'
      responsibilityScore:
        $ref: '#/definitions/services.score'
      score:
        type: integer
      skillsScore:
        $ref: '#/definitions/services.score'
    type: object
  services.Candidate:
    properties:
      education:
        items:
          $ref: '#/definitions/services.Education'
        type: array
      experiences:
        items:
          $ref: '#/definitions/services.Experience'
        type: array
      id:
        type: string
      location:
        type: string
      skills:
        items:
          $ref: '#/definitions/services.Skill'
        type: array
      summary:
        type: string
    type: object
  services.CandidateDto:
    properties:
      education:
        items:
          $ref: '#/definitions/services.Education'
        type: array
      experiences:
        items:
          $ref: '#/definitions/services.Experience'
        type: array
      location:
        type: string
      skills:
        items:
          type: string
        type: array
      summary:
        type: string
    type: object
  services.Dummy:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  services.DummyDto:
    properties:
      name:
        type: string
    type: object
  services.Education:
    properties:
      description:
        type: string
      institute:
        type: string
      title:
        type: string
    type: object
  services.Experience:
    properties:
      company:
        type: string
      description:
        type: string
      endDate:
        type: string
      isCurrent:
        type: boolean
      startDate:
        type: string
      title:
        type: string
    type: object
  services.Job:
    properties:
      description:
        type: string
      elasticId:
        type: string
      id:
        type: string
      location:
        type: string
      locationType:
        type: string
      qualifications:
        items:
          $ref: '#/definitions/services.Qualification'
        type: array
      responsibilities:
        items:
          $ref: '#/definitions/services.Responsibility'
        type: array
      title:
        type: string
      yearsOfExperience:
        type: integer
    type: object
  services.Qualification:
    properties:
      description:
        type: string
    type: object
  services.Responsibility:
    properties:
      description:
        type: string
    type: object
  services.ScrapeSeekPayload:
    properties:
      candidate:
        $ref: '#/definitions/services.Candidate'
      userId:
        type: string
    type: object
  services.ScrapedJob:
    properties:
      company:
        type: string
      description:
        type: string
      location:
        type: string
      title:
        type: string
    type: object
  services.ScrapedJobAssessment:
    properties:
      assessment:
        $ref: '#/definitions/services.Assessment'
      job:
        $ref: '#/definitions/services.Job'
    type: object
  services.Skill:
    properties:
      description:
        type: string
    type: object
  services.match:
    properties:
      isMatch:
        type: boolean
    type: object
  services.point:
    properties:
      explanation:
        type: string
      isValid:
        type: boolean
    type: object
  services.score:
    properties:
      explanation:
        type: string
      score:
        type: integer
    type: object
info:
  contact: {}
paths:
  /assessments/:
    get:
      consumes:
      - application/json
      description: Queries for an existing assessment.
      parameters:
      - description: ID of the job the assessment is based on
        in: query
        name: jobId
        type: string
      - description: The score attained in the assessment
        in: query
        name: score
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/services.Assessment'
            type: array
        "500":
          description: Internal Server Error
      summary: Queries for an existing assessment.
      tags:
      - Assessment
  /assessments/{userId}:
    get:
      consumes:
      - application/json
      description: Gets an existing assessment.
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.Assessment'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Gets an existing assessment.
      tags:
      - Assessment
  /candidates/:
    post:
      consumes:
      - application/json
      description: Creates a candidate.
      parameters:
      - description: Request payload
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/services.CandidateDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/services.Candidate'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Creates a candidate.
      tags:
      - Candidate
  /candidates/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes an existing candidate.
      parameters:
      - description: Candidate ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
      summary: Deletes an existing candidate.
      tags:
      - Candidate
    get:
      consumes:
      - application/json
      description: Gets a candidate.
      parameters:
      - description: Candidate ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/services.Candidate'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Gets a candidate.
      tags:
      - Candidate
  /dummies/:
    post:
      consumes:
      - application/json
      description: Creates a dummy.
      parameters:
      - description: Request payload
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/services.DummyDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/services.Dummy'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Creates a dummy.
      tags:
      - Dummy
  /dummies/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes an existing dummy.
      parameters:
      - description: Dummy ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
      summary: Deletes an existing dummy.
      tags:
      - Dummy
    get:
      consumes:
      - application/json
      description: Gets a dummy.
      parameters:
      - description: Dummy ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/services.Dummy'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Gets a dummy.
      tags:
      - Dummy
    post:
      consumes:
      - application/json
      description: Updates an existing dummy.
      parameters:
      - description: Dummy ID
        in: path
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/services.DummyDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.Dummy'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Updates an existing dummy.
      tags:
      - Dummy
  /health:
    get:
      consumes:
      - application/json
      description: Health check ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Health check
      tags:
      - Health
  /scrape/seek:
    post:
      consumes:
      - application/json
      description: Scrapes a seek job page for Software Engineering Jobs. Accepts
        a "candidate" and ranks the candidate against the job postings.
      parameters:
      - description: Request body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/services.ScrapeSeekPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/services.ScrapedJob'
            type: array
        "400":
          description: Bad Request
      summary: Scrapes a seek job page
      tags:
      - Scrape
  /scrape/seek/{user}:
    get:
      consumes:
      - application/json
      description: Fetches the assessments made for a particular candidate, in relation
        to scraped jobs.
      parameters:
      - description: User ID
        in: path
        name: user
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/services.ScrapedJobAssessment'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Fetches the assessments made for a particular candidate, in relation
        to scraped jobs.
      tags:
      - Scrape
swagger: "2.0"
